language: node_js
node_js:
- node
- lts/node

before_install:
- npm i -g npm
- npm --version

script:
- npm run lint
- npm run compile-check
- npm audit
- npm run coverage

after_success:
- npm run upload-coverage

notifications:
  email: false
